-- Create table for Clinical Profile
create table if not exists perfil_clinico (
  id bigint generated by default as identity primary key,
  paciente_id uuid not null unique, -- Ensure one profile per patient
  nome text,
  data_nascimento date,
  tipagem_sanguinea text,
  dum date,
  dpp date,
  ig_ultrassom text,
  gestas integer,
  partos integer,
  abortos integer,
  partos_normais integer,
  partos_operatorios integer,
  cesareas integer,
  prematuros text,
  amamentou text,
  antecedentes_clinico text,
  antecedentes_cirurgico text,
  alergia_medicamentosa text,
  medicamentos_em_uso text,
  created_at timestamp with time zone default now(),
  updated_at timestamp with time zone default now()
);

-- Enable Row Level Security (RLS)
alter table perfil_clinico enable row level security;

-- Create policies
drop policy if exists "Enable all access for all users" on perfil_clinico;
create policy "Enable all access for all users" on perfil_clinico for all using (true) with check (true);
