-- Create tables for exams

-- Exames Laboratoriais
create table if not exists exames_laboratoriais (
  id bigint generated by default as identity primary key,
  paciente_id uuid not null,
  nome text not null,
  data date not null,
  resultado text,
  arquivo_url text,
  created_at timestamp with time zone default now()
);

-- Exames Clínicos
create table if not exists exames_clinicos (
  id bigint generated by default as identity primary key,
  paciente_id uuid not null,
  nome text not null,
  data date not null,
  valor text,
  observacao text,
  created_at timestamp with time zone default now()
);

-- Exames de Imagem
create table if not exists exames_imagem (
  id bigint generated by default as identity primary key,
  paciente_id uuid not null,
  nome text not null,
  data date not null,
  ig text,
  observacao text,
  arquivo_url text,
  created_at timestamp with time zone default now()
);

-- Consultas
create table if not exists consultas (
  id bigint generated by default as identity primary key,
  paciente_id uuid not null,
  data date not null,
  hora time not null,
  medico text not null,
  local text not null,
  tipo text not null,
  status text not null check (status in ('agendada', 'realizada', 'cancelada')),
  observacoes text,
  created_at timestamp with time zone default now()
);

-- Enable Row Level Security (RLS)
alter table exames_laboratoriais enable row level security;
alter table exames_clinicos enable row level security;
alter table exames_imagem enable row level security;
alter table consultas enable row level security;

-- Create policies (Drop first to avoid "already exists" error)
drop policy if exists "Enable all access for all users" on exames_laboratoriais;
create policy "Enable all access for all users" on exames_laboratoriais for all using (true) with check (true);

drop policy if exists "Enable all access for all users" on exames_clinicos;
create policy "Enable all access for all users" on exames_clinicos for all using (true) with check (true);

drop policy if exists "Enable all access for all users" on exames_imagem;
create policy "Enable all access for all users" on exames_imagem for all using (true) with check (true);

drop policy if exists "Enable all access for all users" on consultas;
create policy "Enable all access for all users" on consultas for all using (true) with check (true);
